### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'tokens' when running results = esm_model(batch_tokens, repr_layers=[33], return_contacts=False) in prediction.py

### ISSUE THREAD

**Issue by ymx0723** [wwzll123/ESM-DBP#1]
Hello,

I'm encountering a TypeError when running the prediction.py script. Specifically, the error occurs at the line:
```python
results = esm_model(batch_tokens, repr_layers=[33], return_contacts=False)
``` 
Here is the error message:
```python
Traceback (most recent call last):
  File "prediction.py", line 83, in <module>
    dbs_pro, dbp_out, tf_out = get_one_prediction_res(pro, seq)
  File "prediction.py", line 65, in get_one_prediction_res
    fea_represent = get_one_protein_esm_fea(pro_name, seq)
  File "prediction.py", line 49, in get_one_protein_esm_fea
    results = esm_model(batch_tokens, repr_layers=[33], return_contacts=False)
  File "/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 186, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 201, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 109, in parallel_apply
    output.reraise()
  File "/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
TypeError: Caught TypeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 84, in _worker
    output = module(*input, **kwargs)
  File "/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() missing 1 required positional argument: 'tokens'

``` 
Could you help with understanding if this is a bug or if there is a different way the input should be provided?

Thank you!

**Comment by wwzll123** [comment]
Hi,

Thanks for your interest!

This seems like a bug of python.

I recommend you to add the positional argument name in the line 49 of “prediction.py”. That is “esm_model(tokens=batch_tokens, repr_layers=[33], return_contacts=False)”.

It may help you for run correctly.

Your Sincerely,

Wenwu Zeng

Hunan University

---- Replied Message ----
| From | ***@***.***> |
| Date | 09/12/2024 15:30 |
| To | wwzll123/ESM-DBP ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [wwzll123/ESM-DBP] TypeError: forward() got an unexpected keyword argument 'tokens' when running results = esm_model(batch_tokens, repr_layers=[33], return_contacts=False) in prediction.py (Issue #1) |

Hello,

I'm encountering a TypeError when running the prediction.py script. Specifically, the error occurs at the line:

results=esm_model(batch_tokens, repr_layers=[33], return_contacts=False)

Here is the error message:

Traceback (mostrecentcalllast):
  File"prediction.py", line83, in<module>dbs_pro, dbp_out, tf_out=get_one_prediction_res(pro, seq)
  File"prediction.py", line65, inget_one_prediction_resfea_represent=get_one_protein_esm_fea(pro_name, seq)
  File"prediction.py", line49, inget_one_protein_esm_fearesults=esm_model(batch_tokens, repr_layers=[33], return_contacts=False)
  File"/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/modules/module.py", line1553, in_wrapped_call_implreturnself._call_impl(*args, **kwargs)
  File"/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/modules/module.py", line1562, in_call_implreturnforward_call(*args, **kwargs)
  File"/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line186, inforwardoutputs=self.parallel_apply(replicas, inputs, module_kwargs)
  File"/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line201, inparallel_applyreturnparallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File"/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line109, inparallel_applyoutput.reraise()
  File"/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/_utils.py", line706, inreraiseraiseexceptionTypeError: CaughtTypeErrorinreplica1ondevice1.OriginalTraceback (mostrecentcalllast):
  File"/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line84, in_workeroutput=module(*input, **kwargs)
  File"/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/modules/module.py", line1553, in_wrapped_call_implreturnself._call_impl(*args, **kwargs)
  File"/share/home/yumeixia/miniconda3/envs/crisprcasfinder/envs/ESM_DBP/lib/python3.8/site-packages/torch/nn/modules/module.py", line1562, in_call_implreturnforward_call(*args, **kwargs)
TypeError: forward() missing1requiredpositionalargument: 'tokens'

Could you help with understanding if this is a bug or if there is a different way the input should be provided?

Thank you!
